# .github/dependabot.yml
version: 2
updates:
  # --- NPM dependencies ---
  - package-ecosystem: "npm"
    directory: "/"  # location of package.json
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"  # ignore all non-security updates
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
    commit-message:
      prefix: "deps"

  # --- Docker dependencies ---
  - package-ecosystem: "docker"
    directory: "/"  # location of Dockerfile
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docker-deps"
