# .github/dependabot.yml
version: 2
updates:
  # --- Python dependencies ---
  - package-ecosystem: "pip"
    directory: "/"  # where requirements.txt is located
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5

  # --- Docker dependencies ---
  - package-ecosystem: "docker"
    directory: "/"  # where your Dockerfile is located
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docker-deps"
    open-pull-requests-limit: 5
